c:	
	gcc mypwd_16CS60R54.c -o mypwd
	gcc mymkdir_16CS60R54.c -o mymkdir
	gcc myls_16CS60R54.c -o myls
	gcc myrm_16CS60R54.c -o myrm
	gcc mytail_16CS60R54.c -o mytail
	gcc mymv_16CS60R54.c -o mymv
	gcc myps_16CS60R54.c -o myps
	gcc mygrep_16CS60R54.c -o mygrep
	gcc MyPipe_16CS60R54.c -o mypipe
	gcc MainTest_16CS60R54.c -o MainTest
	gcc SedDelete_16CS60R54.c -o SedDelete
	gcc LinesDelete_16CS60R54.c -o LinesDelete
	gcc FourB1_16CS60R54.c -o FourB1
	gcc FourB2_16CS60R54.c -o FourB2
	gcc FourB3_16CS60R54.c -o FourB3
	./MainTest
